### ISSUE TITLE
本地跑puppeteer-demo，初始化.env，但是跑不起来

### ISSUE THREAD

**Issue by GeeFib** [web-infra-dev/midscene-example#14]
初始化env文件后，荏苒跑不起来，是还需要什么变量吗？
### .env 
OPENAI_API_KEY="xxxxx"

####
错误信息：
Error: Cannot find Coze or OpenAI config. You should set at least one of them.
Error: Cannot find Coze or OpenAI config. You should set at least one of them.
    at callAiFn (C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\node_modules\@midscene\core\dist\lib\index.js:4444:9)
    at plan (C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\node_modules\@midscene\core\dist\lib\index.js:5705:22)
    at async Object.executor (C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\node_modules\@midscene\web\dist\lib\puppeteer.js:786:24
)
    at async Executor.flush (C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\node_modules\@midscene\core\dist\lib\index.js:5415:25)
    at async PageTaskExecutor.action (C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\node_modules\@midscene\web\dist\lib\puppeteer.j
s:812:18)
    at async PuppeteerAgent.aiAction (C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\node_modules\@midscene\web\dist\lib\puppeteer.j
s:1126:26)
    at <anonymous> (c:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\demo.ts:26:5)
    at PuppeteerAgent.aiAction (C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\node_modules\@midscene\web\dist\lib\puppeteer.js:1131
:13)
    at <anonymous> (c:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\demo.ts:26:5)

Node.js v18.0.0
error Command failed with exit code 1.

#### 继续排查：
midscene-example-main\midscene-example-main\puppeteer-demo\node_modules\@midscene\core\dist\lib\index.js
按照文件还需要OPENAI_BASE_URL，配置
OPENAI_BASE_URL="https://api.openai.com/v1"
依然报错

请求给一份完整的配置

**Comment by yuyutaotao** [comment]
你好， 原本 Puppeteer 的用例里没有读取 dotenv 文件，需要配系统环境变量才能跑。

刚才 Demo 已经更新了，支持读取环境变量，拉一下代码就行。

你的配置内容是对的，可以只写 OPENAI_API_KEY ，不用改

**Comment by GeeFib** [comment]
拉了新代码，配了key依然报错

开了代理，同样的key使用chrome 插件是跑的通的
Error: Connection error.
C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\node_modules\openai\src\core.ts:441
      throw new APIConnectionError({ cause: response });
            ^

Error: Connection error.
    at OpenAI.makeRequest (C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\node_modul
es\openai\src\core.ts:441:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async call (C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\node_modules\@mids
cene\core\dist\lib\index.js:5122:22)
    at async callToGetJSONObject (C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\nod
e_modules\@midscene\core\dist\lib\index.js:5163:20)
    at async callAiFn (C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\node_modules\@
midscene\core\dist\lib\index.js:4419:25)
    at async plan (C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\node_modules\@mids
cene\core\dist\lib\index.js:5705:16)
    at async Object.executor (C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\node_mo
dules\@midscene\web\dist\lib\puppeteer.js:786:24)
    at async Executor.flush (C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\node_mod
ules\@midscene\core\dist\lib\index.js:5415:25)
    at async PageTaskExecutor.action (C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo
\node_modules\@midscene\web\dist\lib\puppeteer.js:812:18)
    at async PuppeteerAgent.aiAction (C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo
\node_modules\@midscene\web\dist\lib\puppeteer.js:1126:26)
    at PuppeteerAgent.aiAction (C:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\node_
modules\@midscene\web\dist\lib\puppeteer.js:1131:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (c:\Users\Administrator\Desktop\gpt4vtest\midscene-example-main\midscene-example-main\puppeteer-demo\demo.ts:27:5)

Node.js v18.0.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by yuyutaotao** [comment]
Error: Connection error. 看起来就是网络问题，得你看看网络环境了。改 OpenAI 的环境变量会有用吗？
```bash
OPENAI_BASE_URL='https://your-custom-endpoint.com'
```

**Comment by GeeFib** [comment]
我用的就是直连的key呢，全局开了代理了，同样的key chrome插件斯可行的。

**Comment by GeeFib** [comment]
是本身有配置代理吗

**Comment by yuyutaotao** [comment]
如果用的是代理，可以试一下这个包：

@midscene/web@0.8.5-beta-20241203162056.0

在环境变量里配置代理，如：

MIDSCENE_OPENAI_SOCKS_PROXY="socks5://127.0.0.1:1080"

如果是VPN，那还得你自己检查下网络连通性。

**Comment by GeeFib** [comment]
node版本有要求吗？目前用的18.0.0

**Comment by yuyutaotao** [comment]
18 应该是没问题的
