### ISSUE TITLE
puppeteer-demo 运行失败，辛苦帮忙看下

### ISSUE THREAD

**Issue by hankunfang** [web-infra-dev/midscene-example#24]
Error
400 Missing required parameter: 'response_format.json_schema'. (request id: 2024122010154217363454491285978)

➜  puppeteer-demo git:(main) ✗ npx tsx demo.ts
(node:11133) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Midscene - report file updated: /Users/hankunfang/workspace/midscene-example/puppeteer-demo/midscene_run/report/web-2024-12-20_10-15-40-231.html
/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/@midscene/web/dist/lib/puppeteer.js:1291
      throw new Error(`${errorTask == null ? void 0 : errorTask.error}
            ^

Error: 400 Missing required parameter: 'response_format.json_schema'. (request id: 2024122010154217363454491285978)
Error: 400 Missing required parameter: 'response_format.json_schema'. (request id: 2024122010154217363454491285978)
    at Function.generate (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/openai/src/error.ts:70:14)

**Comment by hankunfang** [comment]
/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/@midscene/web/dist/lib/puppeteer.js:1291
      throw new Error(`${errorTask == null ? void 0 : errorTask.error}
            ^

Error: 400 Missing required parameter: 'response_format.json_schema'. (request id: 202412201428294827994785579509)
Error: 400 Missing required parameter: 'response_format.json_schema'. (request id: 202412201428294827994785579509)
    at Function.generate (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/openai/src/error.ts:70:14)
    at OpenAI.makeStatusError (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/openai/src/core.ts:397:21)
    at OpenAI.makeRequest (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/openai/src/core.ts:460:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async call (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/@midscene/core/dist/lib/index.js:5530:22)
    at async callToGetJSONObject (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/@midscene/core/dist/lib/index.js:5576:20)
    at async callAiFn (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/@midscene/core/dist/lib/index.js:5608:32)
    at async plan (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/@midscene/core/dist/lib/index.js:5895:30)
    at async Object.executor (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/@midscene/web/dist/lib/puppeteer.js:839:24)
    at async Executor.flush (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/@midscene/core/dist/lib/index.js:4607:25)
    at PuppeteerAgent.aiAction (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/@midscene/web/dist/lib/puppeteer.js:1291:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async <anonymous> (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/demo.ts:28:5)

**Comment by yuyutaotao** [comment]
在另一个 issue 跟进：https://github.com/web-infra-dev/midscene/issues/196

另，可以参照文档测试可连接性的问题： https://midscenejs.com/model-provider.html
